### PR TITLE
Update grunt-contrib-compress to v1.4.3

### PR DESCRIPTION
**Pull request by jacek-pulit**
This is dependency update grunt-contrib-compress to v1.4.3 that uses archiver v1.3.0 
It fixes an issue with empty tgz files.

### CODE REVIEW

**Comment by jacek-pulit** [comment]
@pbomb Yey, are you able to squash and merge this change and then publish new version to the npm ?

**Comment by pbomb** [comment]
I don't think I have access anymore, but I'll try to get ahold of someone who does.

**Comment by pbomb** [comment]
@robertfwest Could you make a new release and publish it to npm?

**Comment by robertfwest** [comment]
Just published 1.1.0

**Comment by pbomb** [comment]
:+1: thanks!

**Comment by jacek-pulit** [comment]
@robertfwest Thank you! 👍

**Pull request merged**
